### ISSUE TITLE
How to include CSS ?

### ISSUE THREAD

**Issue by tflorac** [volodalexey/react-remote-component#1]
Hi,
I found your code sample and think it's very interesting!
But I'm new to React and can't get to include any CSS styling into my component, class names or styles are always ignored into final rendering!!
Any idea?
Best regards,
Thierry

**Comment by volodalexey** [comment]
Hi @tflorac , I do not know how to do this.
Try to use [react-helmet](https://github.com/nfl/react-helmet) library, or do it manually:
```
componentDidMount() {
  const style = document.createElement('style');
  style.type = 'text/css';
  style.appendChild(document.createTextNode(' a { background-color: black; } '));
  document.head.appendChild(style);
 }
```

**Comment by tflorac** [comment]
OK, thanks!
